### ISSUE TITLE
Need the specific of the resistance

### ISSUE THREAD

**Issue by robertlee2014** [neg2led/cfxsx#1]
Hi，where can I get the electric resistance value？ I have try to make it in ubuntu 20 with KiKit python module installed but faild. And I have got a 2230 m.2 SSD which is part of a XSX console. So I really need ur help for some sepcs.

**Comment by neggles** [comment]
Do you mean the PCIe trace impedance?

The trace widths and spacing on this board were chosen so that if you have it made by JLCPCB, using their 'JLC2313' controlled-impedance board stackup, the data pairs will have a differential impedance of 84 ohms, and the clock pair will have a differential impedance of 90 ohms.

These are both well within the recommended ranges according to the "PCI Express Card Electromechanical Specification Revision 3.0" document (and are unchanged for PCIe 4.0, as far as I'm aware), and the traces here are very short anyway so it should be fine.

I haven't had any of these made yet, though, so I don't know for sure that it works.

Edit: you can also download prebuilt .zips of gerbers from https://neg2led.github.io/cfxsx/

**Comment by robertlee2014** [comment]
Okay，I installed Kicad and now I can access to the full pcb prj and found there are 4 electric capacities. So when after testing this pcb, I will share my result here. Thanks.
